In [2]:
import kickass as ks

import json
fd = open("../data/project_successful_final_tech_sample.json", "r")

project_json = json.load(fd)

ks_projects = ks.ProjectCollection(project_json, "../data/stopwords.txt")

In [48]:
X = ks.np.array([[10,5,0,0,1,0], [0,5,14,2,0,0], [1,1,0,10,20,2], [0,1,0,5,21,7]])
U, s, V = ks.np.linalg.svd(X, full_matrices=True)

In [49]:
Ud = U[:, :2]
sd = s[:2]
Vd = V[:2, :]
S = ks.np.diag(sd)
print(ks.np.shape(Ud), ks.np.shape(sd), ks.np.shape(Vd))

((4, 2), (2,), (2, 6))


In [69]:
Xstar =  ks.np.dot(Ud, ks.np.dot(S, Vd))
norm = ks.np.sqrt(ks.np.square(Xstar.T).sum(axis = 1))
Xstar =  Xstar.T / norm[:,None]
Xstar

array([[ 0.21491447,  0.87010556,  0.33700071,  0.28837233],
       [ 0.22290546,  0.94043517,  0.20671157,  0.15220108],
       [ 0.21963532,  0.97465284,  0.02311292, -0.03574859],
       [ 0.08192682,  0.18126238,  0.69417531,  0.69177495],
       [ 0.04128806, -0.00231224,  0.70206918,  0.71090703],
       [ 0.03476817, -0.03115061,  0.70102859,  0.71160364]])

In [40]:
Xstar / norm

ValueError: operands could not be broadcast together with shapes (4,6) (4,) 

In [68]:
d = ks.np.array([1, 2, 3, 4])
d = d / ks.np.sqrt(d.sum())
d
sim = ks.np.dot(Xstar, d)
sim

array([ 1.30273729,  1.05389697,  0.66258742,  1.67413424,  1.57686952,
        1.55646271])

In [55]:
print(sim)

[[ 1.          0.97973601  0.89273383  0.60875099  0.44846523  0.42182179]
 [ 0.97973601  1.          0.96489246  0.43751042  0.26035546  0.23167245]
 [ 0.89273383  0.96489246  1.          0.18597636 -0.00237238 -0.03196072]
 [ 0.60875099  0.43751042  0.18597636  1.          0.98211025  0.97610832]
 [ 0.44846523  0.26035546 -0.00237238  0.98211025  1.          0.99956214]
 [ 0.42182179  0.23167245 -0.03196072  0.97610832  0.99956214  1.        ]]


In [ ]:
a = ks.np.random.randn(9, 6) + 1j*ks.np.random.randn(9, 6)
U, s, V = ks.np.linalg.svd(a, full_matrices=True)
print(U.shape, V.shape, s.shape)
S = ks.np.zeros((9, 6), dtype=complex)
S[:6, :6] = ks.np.diag(s)
ks.np.dot(U, ks.np.dot(S, V))